<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => 'CSV',
    'Download {name}' => 'Скачать {name}',
    'Excel' => 'Excel',
    'MS CSV' => 'MS CSV',
    'Administration' => 'Администрирование',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить запись?',
    'Choose {name}' => 'Выберите',
    'Content' => 'Контент',
    'Could not delete {name}.' => 'Не возможно удалить "{name}".',
    'Could not upload file.' => 'Невозможно загрузить файл.',
    'Create {name}' => 'Создать',
    'Delete' => 'Удалить',
    'Delete file' => 'Удалить файл',
    'Delete image' => 'Удалить изображение',
    'Download file' => 'Посмотреть файл',
    'List {name}' => 'Список',
    'Login' => 'Войти',
    'Logout ({username})' => 'Выйти ({username})',
    'Preview image' => 'Посмотреть изображение',
    'Save' => 'ОК',
    'Save and add another' => 'Сохранить и добавить новый',
    'Save and continue editing' => 'Сохранить',
    'Update' => 'Ок',
    'Copy' => 'Скопировать',
    'Update {name}' => '{name}',
    '{name} has been created.' => 'Запись <b>{name}</b> создана.',
    '{name} has been deleted.' => 'Запись <b>{name}</b> удалена.',
    '{name} has been updated.' => 'Запись <b>{name}</b> обновлена.',
    'You can\'t create entries in demo mode' => 'Вы не можете создавать записи в демо режиме',
    'You can\'t edit entries in demo mode' => 'Вы не можете редактировать записи в демо режиме',
    'You can\'t delete entries in demo mode' => 'Вы не можете удалять записи в демо режиме',
    'Entry for copy not found' => 'Запись для копирования не найдена',
    'Add field' => 'Добавить поле',
    'Main' => 'Основное',
    'Language' => 'Язык'
];
